name: Fetch NBA RSS

on:
  schedule:
    - cron: "0 1 * * *"  # 每天 9:00（台灣時間，UTC+8 = UTC 1AM）
  workflow_dispatch:     # 允許手動觸發

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install feedparser
        run: pip install feedparser

      - name: Run RSS Reader
        run: python rss_reader.py
